// Placeholder Firebase options to keep analyzer happy while Firebase is disabled.
// When you enable Firebase, replace this file with the real one generated by FlutterFire CLI.

class FirebaseOptions {
  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  final String? storageBucket;
  final String? authDomain;
  final String? iosBundleId;

  const FirebaseOptions({
    this.apiKey = '',
    this.appId = '',
    this.messagingSenderId = '',
    this.projectId = '',
    this.storageBucket,
    this.authDomain,
    this.iosBundleId,
  });
}

class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions();
  static const FirebaseOptions web = FirebaseOptions();
  static const FirebaseOptions android = FirebaseOptions();
  static const FirebaseOptions ios =
      FirebaseOptions(iosBundleId: 'com.example.iotEWasteMonitor');
  static const FirebaseOptions macos =
      FirebaseOptions(iosBundleId: 'com.example.iotEWasteMonitor');
}
